language: node_js

env:
  - CXX=g++-4.8

git:
  depth: 10

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-4.8

branches:
  only:
    - master
    - /^[0-9]+\.[0-9]+\.[0-9]+.*/

cache:
  directories:
    - node_modules

before_install:
  - bash <(curl -s https://blackbaud.github.io/skyux-travis/before-install.sh)

after_script:
  - bash <(curl -s https://blackbaud.github.io/skyux-travis/after-script.sh)

after_success:
  - bash <(curl -s https://blackbaud.github.io/skyux-travis/after-success.sh)
